export const STORAGE_KEYS = {
  leaderboard: 'cs_leaderboard_v2',
  leaderboardLegacy: 'cs_leaderboard',
  trophies: 'cs_trophies',
  trophyLevels: 'cs_trophy_levels_v1',
  cash: 'cs_cash',
  achievements: 'cs_achievements_v1',
  ultimate: 'cs_ultimate_v1',
  ultimatesOwned: 'cs_ultimates_owned_v1',
  ultimateUpgrades: 'cs_ultimate_upgrades_v1',
  mouseAim: 'cs_mouse_aim_v1',
  maxStartLevel: 'cs_max_start_level_v1',
  playerName: 'cs_player_name_v1',
  storyProgress: 'cs_story_progress_v1',
};

export const COLOR_CASH_VALUES = {
  yellow: 2,
  red: 3,
  green: 3,
  blue: 4,
  black: 5,
  white: 5,
  purple: 6,
  brown: 4,
  pink: 5,
};

export const COLOR_ORDER = [
  'yellow',
  'red',
  'green',
  'blue',
  'black',
  'white',
  'purple',
  'brown',
  'pink',
];

export const TROPHIES = [
  {
    id: 'spark',
    name: 'Spark Shard',
    price: 120,
    maxLevel: 3,
    icon: 'S',
    desc: '+1 starting life',
    effect: { startLives: 1 },
  },
  {
    id: 'prism',
    name: 'Prism Core',
    price: 700,
    maxLevel: 3,
    icon: 'P',
    desc: '+2s powerup duration (all)',
    effect: { powerupDurationBonusMs: 2000 },
  },
  {
    id: 'burn',
    name: 'Afterburner Coil',
    price: 450,
    maxLevel: 3,
    icon: 'A',
    desc: '+3s SPEED powerup duration',
    effect: { powerupDurationByType: { speed: 3000 } },
  },
  {
    id: 'cycler',
    name: 'Cycler Module',
    price: 520,
    maxLevel: 3,
    icon: 'C',
    desc: '+3s FIRERATE powerup duration',
    effect: { powerupDurationByType: { fireRate: 3000 } },
  },
  {
    id: 'pierce',
    name: 'Pierce Capacitor',
    price: 560,
    maxLevel: 3,
    icon: 'I',
    desc: '+3s PIERCING powerup duration',
    effect: { powerupDurationByType: { piercing: 3000 } },
  },
  {
    id: 'scatter',
    name: 'Scatter Matrix',
    price: 600,
    maxLevel: 3,
    icon: 'M',
    desc: '+3s SHOTGUN powerup duration',
    effect: { powerupDurationByType: { shotgun: 3000 } },
  },
  {
    id: 'ricochet',
    name: 'Ricochet Plating',
    price: 600,
    maxLevel: 3,
    icon: 'R',
    desc: '+3s BOUNCE powerup duration',
    effect: { powerupDurationByType: { bounce: 3000 } },
  },
  {
    id: 'anchor',
    name: 'Stasis Anchor',
    price: 680,
    maxLevel: 3,
    icon: 'T',
    desc: '+3s STASIS powerup duration',
    effect: { powerupDurationByType: { stasis: 3000 } },
  },
  {
    id: 'nova',
    name: 'Nova Crown',
    price: 900,
    maxLevel: 3,
    icon: 'N',
    desc: '+15% cash from kills',
    effect: { cashMultiplier: 1.15 },
  },
  {
    id: 'reservoir',
    name: 'Reservoir Lattice',
    price: 800,
    maxLevel: 3,
    icon: 'R',
    desc: '-12% energy drain',
    effect: { energyDrainMultiplier: 0.88 },
  },
];

export const POWERUP_DURATION_MS = 15000;
export const POWERUP_DROP_CHANCE = 0.1;
export const LIFE_DROP_CHANCE = 0.05;

export const POWERUP_TYPES = {
  speed: 'speed',
  fireRate: 'fireRate',
  piercing: 'piercing',
  shotgun: 'shotgun',
  bounce: 'bounce',
  stasis: 'stasis',
  life: 'life',
};
